import type { Metadata } from "next";
import "./globals.css";
import Body from "./body/body";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  views
}: {
  children: React.ReactNode
  views: React.ReactNode
}) {  
  return (
    <html lang="en">
      <Body viewsChildren={views}>{children}</Body>     
    </html>
  );
}
