import type { Metadata } from "next";
import "./globals.css";
import Body from "./body/body";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {  
  console.log("render latoyut");
  return (
    <html lang="en">
      <Body>{children}</Body>     
    </html>
  );
}
