SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE orders;
ALTER TABLE orders AUTO_INCREMENT = 1;
OPTIMIZE TABLE orders;

TRUNCATE TABLE orderItems;
ALTER TABLE orderItems AUTO_INCREMENT = 1;
OPTIMIZE TABLE orderItems;


TRUNCATE TABLE products;
ALTER TABLE products AUTO_INCREMENT = 1;
OPTIMIZE TABLE products;

TRUNCATE TABLE clients;
ALTER TABLE clients AUTO_INCREMENT = 1;
OPTIMIZE TABLE clients;

SET FOREIGN_KEY_CHECKS = 1;